name: "chonk"

loadURDF:
  fileName: "{chonk_description}/urdf/chonk.urdf"   # gets urdf from ros parameter
  useFixedBase: 0
  basePosition: [0, 0, -0.15]

# initial_joint_position:

# initial_revolute_joint_positions_are_deg: true
is_visual_robot: false

setJointMotorControlArray:
  controlMode: "POSITION_CONTROL"

publish_joint_state_frequency: 30

broadcast_link_states: true
brodcast_link_states_frequency: 30
