#
# Basic example
#


#
# Pybullet instance
#
connect:
  connection_mode: 'GUI'
  # options: "--mp4=$HOME/fig8.mp4"

setAdditionalSearchPath: 'pybullet_data_path'

resetSimulation:
  flags: "RESET_USE_DEFORMABLE_WORLD"

setPhysicsEngineParameter:
  sparseSdfVoxelSize: 0.25

setGravity:
  gravX: 0.0
  gravY: 0.0
  gravZ: -10

timeStep: 0.01
start_pybullet_after_initialization: true
status_hz: 50

step_pybullet_manually: True


#
# Pybullet visualizer
#
configureDebugVisualizer:
  enable: 0
  flag: 'COV_ENABLE_GUI'

resetDebugVisualizerCamera:
  cameraDistance: 3
  cameraYaw: -420
  cameraPitch: -30
  cameraTargetPosition: [0.3, 0.8, 0.7]


#
# Pybullet objects
#

urdfs:
  - "{rpbi_examples}/configs/soft_body/plane.yaml"
  - "{rpbi_examples}/configs/soft_body/cube.yaml"
  # - "{rpbi_examples}/configs/soft_body/torus_deform.yaml"  
# collision_objects:
  # - "{rpbi_examples}/configs/soft_body/floor.yaml"
soft_objects:
  - "{rpbi_examples}/configs/soft_body/torus.yaml"



controls:
  robot_name: "kuka"
