name: "torus"

loadSoftBody:
  fileName: "torus/torus_textured.obj"
  basePosition: [0, 0, 2]
  simFileName: "{rpbi_examples}/configs/soft_body/torus.vtk"
  mass: 3
  useNeoHookean: 1
  NeoHookeanMu: 180
  NeoHookeanLambda: 600
  NeoHookeanDamping: 0.01
  collisionMargin: 0.006
  useSelfCollision: 1
  frictionCoeff: 0.5
  repulsionStiffness: 800
