name: "pushing_box"

createVisualShape:
  shapeType: "GEOM_BOX"
  halfExtents: [0.125, 0.125, 0.125]
  rgbaColor: [0.9, 1.0, 0.3, 1.0]

createCollisionShape:
  shapeType: "GEOM_BOX"
  # halfExtents: [0.1, 0.1, 0.075]
  halfExtents: [0.125, 0.125, 0.125]  

baseMass: 0.5
# basePosition: [-0.6, 0.225, 0.3]
basePosition: [-0.6, 0.25, 0.3]

changeDynamics:
  lateralFriction: 1.0
  spinningFriction: 0.0
  rollingFriction: 0.0
  restitution: 0.0
  linearDamping: 0.04
  angularDamping: 0.04
  contactStiffness: 2000.0
  contactDamping: 0.7
