name: "goal_box"

createVisualShape:
  shapeType: "GEOM_BOX"
  halfExtents: [0.125, 0.125, 0.125]
  rgbaColor: [0, 1.0, 0., 0.5]

createCollisionShape:
  shapeType: "GEOM_BOX"
  # halfExtents: [0.1, 0.1, 0.075]
  halfExtents: [0.125, 0.125, 0.125]  


object_tf:
  tf_id: "goal_box"
  hz: 10
