name: "kuka_lwr"

loadURDF:
  fileName: "{rpbi_examples}/robots/kuka_lwr.urdf"
  useFixedBase: 1
  basePosition: [0.5, 0., 0.]  # can also specify offset in object_tf

initial_joint_position:
  lwr_arm_0_joint: -67.43029874237594
  lwr_arm_1_joint: -43.27708308875299
  lwr_arm_2_joint: 109.3690545555588
  lwr_arm_3_joint: -119.9388173764962
  lwr_arm_4_joint: 77.07446236689286
  lwr_arm_5_joint: -34.464300806724026
  lwr_arm_6_joint: -21.86171402255347



is_visual_robot: false

setJointMotorControlArray:
  controlMode: "POSITION_CONTROL"

publish_joint_state_frequency: 30

publish_link_states: true
