name: "talos"

loadURDF:
  fileName: 'robot_description'
  useFixedBase: 1  # use 1 (fixed base) only for demo
  basePosition: [0, 0, 1.1]

is_visual_robot: false

setJointMotorControlArray:
  controlMode: "POSITION_CONTROL"

publish_joint_state_frequency: 30

broadcast_link_states: true
brodcast_link_states_frequency: 30
