estimation:
  condition: -1.0

object:
  hangPoint: [ 0, 0, 3.8 ]
  ropeLength: 3.0
  startAngle: -20.0
  finObjPos: [0., 0.0, 0.7, 0, 0, 0]
  # finObjPos: [0.2, 0.0, 1.6, 3.14, 0, 0]
  maxObjPos: [2, 2, 2, 6.28, 6.28, 6.28]
  finObjVel: [0., 0., 0., 0., 0., 0.]
  maxObjVel: [1.5, 1.5, 1.5, 1.5, 1.5, 1.5]
  slackObjPos: [0.2, 0.2, 0.2, 0.14, 0.14, 0.14]
  slackObjVel: [0.001, 0.001, 0.001, 0.001, 0.001, 0.001]
  reducedNode: 10

robotYin:
  workspace: 1.0
  minWorkspace: [-0.8, -0.5, -0.2]
  maxWorkspace: [0.8, 0.5, 0.8]

robotYang:
  workspace: 1.0
  minWorkspace: [-0.8, -0.5, -0.2]
  maxWorkspace: [0.8, 0.5, 0.8]
