estimation:
#  condition: 0.95 #0.85
  conditionPos: 0.55 # simulation

  #-----------------------------------------------------------------------------
  # used for negative rotation
  conditionVel: 0.9 # checks only angular velocity along z
  # used for positive rotation
  # conditionVel: 1.0 # checks only angular velocity along z
  # used for comparison experiments and initial orientation
  # conditionVel: 0.05 # checks only linear velocity along y


  #-----------------------------------------------------------------------------
  # used for rotation positive or negative
  uncertainty: 0.05
  # used for comparison and initial rotation experiments
  # uncertainty: 0.025
  # used for initial experiment
  # uncertainty: 0.10


object:


  #-----------------------------------------------------------------------------
  # used for negative rotation
  finObjPos: [-0.2, 2.1, 1.0, 0.0, 0, 0]
  slackObjPos: [0.05, 0.1, 0.2, 0.54, 0.54, 0.24] # with final pose target for rotation experiments
  reducedNode: 22

  # used for positive rotation
  # finObjPos: [-0.3, 2.2, 1.1, 0.3, 0, 0]
  # slackObjPos: [0.05, 0.1, 1.0, 0.24, 0.24, 0.24] # with final pose target for rotation experiments
  # reducedNode: 20

  # used for comparison experiments and initial orientation
  # finObjPos: [-0.3, 2.3, 1.1, 0, 0, 0]
  # slackObjPos: [0.05, 1.1, 0.2, 3.14, 3.14, 3.14] # with final pose target - comparison experiments
  # reducedNode: 30

  # used for high speed experiments
  # finObjPos: [-0.3, 2.3, 1.1, 0, 0, 0]
  # slackObjPos: [0.05, 0.1, 0.2, 3.14, 3.14, 3.14] # with final pose target - high speed experiments
  # maxObjPos: [1.01, 2.3, 1.2, 10, 10, 10]
  # reducedNode: 10

  maxObjPos: [5,5,5, 10, 10, 10]
  finObjVel: [0., 0., 0., 0., 0., 0.]
  maxObjVel: [5, 5, 5, 5, 5, 5]
  slackObjVel: [0.01, 0.01, 0.01, 0.01, 0.01, 0.01]

#-----------------------------------------------------------------------------
# used for comparison experiments, initial orientation and high speed experiments

# robotYin:
#   workspace: 1.4
#   minWorkspace: [-1.1, -0.75, -0.8]
#   maxWorkspace: [1.1, 0.3, 1.9]
#
# robotYang:
#   workspace: 1.4
#   minWorkspace: [-1.1, -0.75, -0.8]
#   maxWorkspace: [1.1, 0.3, 1.9]

# used for rotation positive or negative
robotYin:
  workspace: 1.4
  minWorkspace: [-1.1, -0.75, -0.5]
  maxWorkspace: [1.1, 0.2, 0.3]

robotYang:
  workspace: 1.4
  minWorkspace: [-1.1, -0.75, -0.5]
  maxWorkspace: [1.1, 0.2, 0.3]
