estimation:
#  condition: 0.95 #0.85
  conditionPos: 0.55 # simulation
  conditionVel: 0.05 # simulation
  uncertainty: 0.12

object:
  finObjPos: [-0.3, 2.5, 1.0, 0, 0, 0]
  # finObjPos: [-0.3, 2.4, 1.0, 0, 0, 0]
  maxObjPos: [1.01, 10, 10, 10, 10, 10]
  finObjVel: [0., 0., 0., 0., 0., 0.]
  maxObjVel: [10, 10, 10, 10, 10, 10]
  slackObjPos: [0.03, 0.1, 0.1, 3.14, 3.14, 3.14]
  # slackObjPos: [1.03, 1.1, 1.1, 3.14, 3.14, 3.14] # without final pose target
  slackObjVel: [0.01, 0.01, 0.01, 0.01, 0.01, 0.01]
  reducedNode: 30 # 30

robotYin:
  workspace: 1.5
  minWorkspace: [-1.5, -1.0, -0.8]
  maxWorkspace: [1.5, 1.0, 1.9]

robotYang:
  workspace: 1.5
  minWorkspace: [-1.5, -1.0, -0.8]
  maxWorkspace: [1.5, 1.0, 1.9]
