estimation:
#  condition: 0.95 #0.85
  conditionPos: 0.55 # simulation
  conditionVel: 0.05 # simulation
  uncertainty: 0.025 # 0.10

object:
  # finObjPos: [-0.3, 2.5, 1.0, 0, 0, 0]
  finObjPos: [-0.3, 2.3, 1.1, 0, 0, 0] # --- - comparison experiments
  # finObjPos: [-0.2, 2.2, 1.1, 0.2, 0, 0] # --- rotation experiments
  
  maxObjPos: [1.01, 10, 10, 10, 10, 10]
  finObjVel: [0., 0., 0., 0., 0., 0.]
  maxObjVel: [10, 10, 10, 10, 10, 10]
  # slackObjPos: [0.03, 0.1, 0.1, 3.14, 3.14, 3.14]
  slackObjPos: [0.05, 1.1, 0.2, 3.14, 3.14, 3.14] # with final pose target - comparison experiments
  # slackObjPos: [0.05, 0.1, 1.0, 0.04, 3.14, 3.14] # with final pose target for rotation experiments
  slackObjVel: [0.01, 0.01, 0.01, 0.01, 0.01, 0.01]
  reducedNode: 30 # 30

robotYin:
  workspace: 1.4
  minWorkspace: [-1.4, -0.9, -0.8]
  maxWorkspace: [1.4, 0.9, 1.9]

robotYang:
  workspace: 1.4
  minWorkspace: [-1.4, -0.9, -0.8]
  maxWorkspace: [1.4, 0.9, 1.9]
