estimation:
#  condition: 0.95 #0.85
  condition: -1.0 # simulation
  uncertainty: 0.12

object:
  finObjPos: [0., 0.9, 0.3, 0, 0, 0]
#  finObjPos: [0.2, 0.0, 1.4, 3.14, 0, 0]
  maxObjPos: [0.01, 10, 10, 10, 10, 10]
  finObjVel: [0., 0., 0., 0., 0., 0.]
  maxObjVel: [10, 10, 10, 10, 10, 10]
  slackObjPos: [0.1, 0.1, 0.1, 3.14, 3.14, 3.14]
  slackObjVel: [0.01, 0.01, 0.01, 0.01, 0.01, 0.01]
  reducedNode: 15

robotYin:
  workspace: 1.3
  minWorkspace: [-1.2, -1.0, -0.8]
  maxWorkspace: [1.2, 1.0, 0.9]

robotYang:
  workspace: 1.3
  minWorkspace: [-1.2, -1.0, -0.8]
  maxWorkspace: [1.2, 1.0, 0.9]
