#
# PyBullet KUKA configuration file
#

urdf: "/home/chris/Projects/kuka_ws/src/ros_pybullet_interface/robots/kuka_lwr_force/kuka.urdf"
use_fixed_base: True
base_position: [0.0, 0.0, 0.0]
init_position: [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0]

sensors:

  joint_force_torque_sensor_end_effector:
    joint_index: 8
