#
# PyBullet KUKA configuration file
#

urdf_file_name: "/home/chris/Projects/kuka_ws/src/ros_pybullet_interface/robots/kuka_lwr_force/kuka.urdf"
use_fixed_base: True
base_position: [0.0, 0.0, 0.0]
base_orientation: [0.0, 0.0, 0.0, 1.0]
init_position: [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0]

sensors:

  # 
  # You can have multiple sensors on the robot, each attribute label should be
  # specified as follows
  # 
  #     SENSOR_TYPE__LABEL
  #
  # where SENSOR_TYPE is one of the following
  # 
  #  - joint_force_torque_sensor
  #  
  # and LABEL is some unique label. Each sensor type requires certain arguments
  # to be set, see below.
  #
  #  - joint_force_torque_sensor
  #    - joint_index (int, joint index where F/T sensor is attached on the robot)
  #
  # If the robot has no additional sensors then do not specify the sensors
  # attribute.

  joint_force_torque_sensor__end_effector:
    joint_index: 8
