#
# PyBullet KUKA configuration file
#

file_name: "robots/kuka_lwr_force/kuka_push.urdf"
end_effector: "end_effector_sponge"
use_fixed_base: True
base_position: [0.0, 0.0, 0.0]
base_orient_eulerXYZ: [0.0, 0.0, 0.0]
init_position: [1.31280589, -49.83176737, -7.65876425, 71.40585079, 7.81488752, -44.31203921, -8.3018490]


sensors:

  #
  # You can have multiple sensors on the robot, each attribute label should be
  # specified as follows
  #
  #     SENSOR_TYPE__LABEL
  #
  # where SENSOR_TYPE is one of the following
  #
  #  - joint_force_torque_sensor
  #
  # and LABEL is some unique label. Each sensor type requires certain arguments
  # to be set, see below.
  #
  #  - joint_force_torque_sensor
  #    - joint_index (int, joint index where F/T sensor is attached on the robot)
  #
  # If the robot has no additional sensors then do not specify the sensors
  # attribute.

  joint_force_torque_sensor__end_effector:
    joint_index: 8
