#
# Trajectory manager configuration file for the box
#

motion_dimensions:
  number: 6

  trans:
    translationX:
    translationX_index: 0
    translationY:
    translationY_index: 1
    translationZ:
    translationZ_index: 2

  rotation:
    rotation_repr: 'None'
    rotationvec: [ 1.0, 0.0, 0.0 ]  # unit vector
    rotationangle: 180.0
    rotationvec_index: [ ]

##  'Quat' and [3,7] for quaternion, 'Euler' and [3,6] for euler angles
#  rotation:
#    rotation_repr: 'Quat'
#    rotationvec:
#    rotationangle:
#    rotationvec_index: [3,7]


interpolation:
  nochange_window_length: 1
  use_interpolation: True
  interDt: 0.01

communication:
  publisher:
    header_frame_id: 'ros_pybullet_interface/world'
    msg_child_frame_id: 'ros_pybullet_interface/sphere2'

  listener:
      topic: 'yin_visual/ros_pybullet_interface/end_effector/traj'
      # topic: 'yin/ros_pybullet_interface/end_effector/traj'
