name: "myumi"

loadURDF:
  fileName: 'robot_description' #"{abb_mp_myumi_description}/urdf/myumi_v2.urdf"
  useFixedBase: 1

is_visual_robot: false

setJointMotorControlArray:
  controlMode: "POSITION_CONTROL"

publish_joint_state_frequency: 30

broadcast_link_states: true
brodcast_link_states_frequency: 30
