#
# Basic example
#


#
# Pybullet instance
#
connect:
  connection_mode: 'GUI'

setGravity:
  gravX: 0.0
  gravY: 0.0
  gravZ: -9.81

timeStep: 0.01
start_pybullet_after_initialization: true
status_hz: 50


#
# Pybullet visualizer
#
configureDebugVisualizer:
  enable: 0
  flag: 'COV_ENABLE_GUI'

resetDebugVisualizerCamera:
  cameraDistance: 2.0
  cameraYaw: 0.0
  cameraPitch: -45.0
  cameraTargetPosition: [0.0, 0.0, 0.0]


#
# Pybullet objects
#

robots:
  - "{rpbi_examples}/configs/basic_example_abb_yumi/abb_yumi.yaml"
