name: "kinova"

#
# This example requires the kortex_descrition ROS package.
# https://github.com/Kinovarobotics/ros_kortex/tree/noetic-devel/kortex_description
#

loadURDF:
  fileName: "robot_description"   # gets urdf from ros parameter
  useFixedBase: 1

initial_joint_position:
  joint_1: -45.0
  joint_2: -30
  # joint_3: 
  joint_4: 90.
  joint_5: 0
  joint_6: 45
  joint_7: 90

initial_revolute_joint_positions_are_deg: true
is_visual_robot: true

setJointMotorControlArray:
  controlMode: "POSITION_CONTROL"

publish_joint_state_frequency: 30

broadcast_link_states: true
brodcast_link_states_frequency: 30
