name: "talos"

loadURDF:
  fileName: 'robot_description'
  useFixedBase: 1  # use 1 (fixed base) only for demo
  basePosition: [0, 0, 1.1]

is_visual_robot: false

# initial_joint_position:
  # torso_1_joint: 30
  # torso_2_joint
  # imu_joint
  # head_1_joint
  # head_2_joint
  # rgbd_joint
  # rgbd_optical_joint
  # rgbd_depth_joint
  # rgbd_depth_optical_joint
  # rgbd_rgb_joint
  # rgbd_rgb_optical_joint
  # arm_left_1_joint
  # arm_left_2_joint
  # arm_left_3_joint
  # arm_left_4_joint
  # arm_left_5_joint
  # arm_left_6_joint
  # arm_left_7_joint
  # wrist_left_ft_joint
  # wrist_left_tool_joint
  # gripper_left_base_link_joint
  # gripper_left_joint
  # gripper_left_inner_double_joint
  # gripper_left_fingertip_1_joint
  # gripper_left_fingertip_2_joint
  # gripper_left_motor_single_joint
  # gripper_left_inner_single_joint
  # gripper_left_fingertip_3_joint
  # arm_right_1_joint
  # arm_right_2_joint
  # arm_right_3_joint
  # arm_right_4_joint
  # arm_right_5_joint
  # arm_right_6_joint
  # arm_right_7_joint
  # wrist_right_ft_joint
  # wrist_right_tool_joint
  # gripper_right_base_link_joint
  # gripper_right_joint
  # gripper_right_inner_double_joint
  # gripper_right_fingertip_1_joint
  # gripper_right_fingertip_2_joint
  # gripper_right_motor_single_joint
  # gripper_right_inner_single_joint
  # gripper_right_fingertip_3_joint
  # leg_left_1_joint
  # leg_left_2_joint
  # leg_left_3_joint
  # leg_left_4_joint
  # leg_left_5_joint
  # leg_left_6_joint
  # leg_left_sole_fix_joint
  # leg_right_1_joint
  # leg_right_2_joint
  # leg_right_3_joint
  # leg_right_4_joint
  # leg_right_5_joint
  # leg_right_6_joint
  # leg_right_sole_fix_joint

initial_revolute_joint_positions_are_deg: true

setJointMotorControlArray:
  controlMode: "POSITION_CONTROL"

publish_joint_state_frequency: 30

broadcast_link_states: true
brodcast_link_states_frequency: 30
