name: "box"

createVisualShape:
  shapeType: "GEOM_BOX"
  halfExtents: [0.1, 0.1, 0.06]
  rgbaColor: [0.1, 0.2, 0.4, 1.0]


createCollisionShape:
  shapeType: "GEOM_BOX"
  halfExtents: [0.1, 0.1, 0.06]


changeDynamics:
  lateralFriction: 1.0
  spinningFriction: 0.0
  rollingFriction: 0.0
  restitution: 0.0
  linearDamping: 0.04
  angularDamping: 0.04
  contactStiffness: 2000.0
  contactDamping: 0.7

object_tf:
  tf_id: "box"
  broadcast_tf: true
