name: "kinova"

#
# This example requires the kortex_descrition ROS package.
# https://github.com/Kinovarobotics/ros_kortex/tree/noetic-devel/kortex_description
#

loadURDF:
  fileName: "robot_description"   # gets urdf from ros parameter
  useFixedBase: 1

# initial_joint_position:

# initial_revolute_joint_positions_are_deg: true
is_visual_robot: false

setJointMotorControlArray:
  controlMode: "POSITION_CONTROL"

publish_joint_state_frequency: 30

broadcast_link_states: true
brodcast_link_states_frequency: 30
