name: 'dynamic_sphere'

baseMass: 1.0

createVisualShape:
  shapeType: "GEOM_SPHERE"
  radius: 0.3
  rgbaColor: [0.0, 1.0, 1.0, 1.0]

createCollisionShape:
  shapeType: "GEOM_SPHERE"
  radius: 0.3

changeDynamics:
  lateralFriction: 1.0
  spinningFriction: 0.0
  rollingFriction: 0.0
  restitution: 0.0
  linearDamping: 0.04
  angularDamping: 0.04
  contactStiffness: 2000.0
  contactDamping: 0.7

linear_offset: [0.0, 0.0, 1.0]
