name: "human"

loadURDF:
  fileName: "{rpbi_examples}/robots/human_model.urdf"
  useFixedBase: 1
  basePosition: [0.5, 0., 1.]

is_visual_robot: false

setJointMotorControlArray:
  controlMode: "POSITION_CONTROL"

publish_joint_state_frequency: 30

broadcast_link_states: true
brodcast_link_states_frequency: 30
